CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -g
TARGET = driver_db
SRCS = main.cpp Address.cpp CountyList.cpp Date.cpp DateList.cpp DriverDatabase.cpp
OBJS = $(SRCS:.cpp=.o)

all: $(TARGET)
	@echo "Build complete!"

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	@rm -f *.o $(TARGET)

run: $(TARGET)
	@./$(TARGET)

.PHONY: all clean run
